/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author VINDANV
 */
public class data_barang_layanan extends javax.swing.JFrame {
Connection con = koneksi.getConnection();
Statement stt;
ResultSet rss;
DefaultTableModel modelbarang, modellay, ModelOperator;
public int pilih;
    /**
     * Creates new form data_barang
     */
    public data_barang_layanan() {
        initComponents();
        panel_barang.setVisible(false);
        panel_layanan.setVisible(false);
        panel_operator.setVisible(false);
        tabel_barang();
        tampil_tabel_barang();
        tabel_layanan();
        tampil_tabel_layanan();
        Tabel_Operator();
        Tampil_Tabel_Operator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content_Layer = new javax.swing.JPanel();
        panel_home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panel_layanan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabellayanan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        form_nama_lay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        form_harga_lay = new javax.swing.JTextField();
        add_lay = new javax.swing.JButton();
        delete_lay = new javax.swing.JButton();
        update_lay = new javax.swing.JButton();
        panel_barang = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        form_nama_brg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        form_harga_brg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        add_brg = new javax.swing.JButton();
        delete_brg = new javax.swing.JButton();
        update_brg = new javax.swing.JButton();
        panel_operator = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabelOperator = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        Form_Nama_OP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Form_Username_OP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Form_Password_OP = new javax.swing.JTextField();
        Tambah_OP = new javax.swing.JButton();
        Hapus_OP = new javax.swing.JButton();
        Edit_Op = new javax.swing.JButton();
        Panel_Navigation = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tombol_isi_dt1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content_Layer.setPreferredSize(new java.awt.Dimension(722, 343));
        Content_Layer.setLayout(new java.awt.CardLayout());

        panel_home.setPreferredSize(new java.awt.Dimension(722, 490));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/laundry.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADMINISTRATOR TERITORY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(116, 116, 116))
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Content_Layer.add(panel_home, "card2");

        panel_layanan.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA LAYANAN"));

        tabellayanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabellayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellayananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabellayanan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Nama Layanan");

        jLabel5.setText("Harga");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(form_nama_lay)
                    .addComponent(form_harga_lay, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(form_nama_lay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_harga_lay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add_lay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/add.png"))); // NOI18N
        add_lay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_layActionPerformed(evt);
            }
        });

        delete_lay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/del.png"))); // NOI18N
        delete_lay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_layActionPerformed(evt);
            }
        });

        update_lay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/edit.png"))); // NOI18N
        update_lay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_layActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_layananLayout = new javax.swing.GroupLayout(panel_layanan);
        panel_layanan.setLayout(panel_layananLayout);
        panel_layananLayout.setHorizontalGroup(
            panel_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_layananLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_layananLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(add_lay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(update_lay)
                        .addGap(6, 6, 6)
                        .addComponent(delete_lay)))
                .addGap(36, 36, 36)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panel_layananLayout.setVerticalGroup(
            panel_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_layananLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panel_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_layananLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(panel_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_lay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_lay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_lay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        Content_Layer.add(panel_layanan, "card2");

        panel_barang.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(0, 255, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA BARANG"));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelbarang);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 255, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("Harga");

        jLabel6.setText("Nama Barang");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(form_nama_brg)
                    .addComponent(form_harga_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_nama_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_harga_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add_brg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/add.png"))); // NOI18N
        add_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_brgActionPerformed(evt);
            }
        });

        delete_brg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/del.png"))); // NOI18N
        delete_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_brgActionPerformed(evt);
            }
        });

        update_brg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/edit.png"))); // NOI18N
        update_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_brgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_barangLayout = new javax.swing.GroupLayout(panel_barang);
        panel_barang.setLayout(panel_barangLayout);
        panel_barangLayout.setHorizontalGroup(
            panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_barangLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(add_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(update_brg)
                        .addGap(6, 6, 6)
                        .addComponent(delete_brg)))
                .addGap(36, 36, 36)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panel_barangLayout.setVerticalGroup(
            panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barangLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_barangLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(panel_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        Content_Layer.add(panel_barang, "card2");

        panel_operator.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA OPERATOR"));

        TabelOperator.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelOperator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelOperatorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TabelOperator);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(102, 255, 204));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Username");

        jLabel10.setText("Nama");

        jLabel17.setText("Password");

        Form_Password_OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_Password_OPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(12, 12, 12))
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Form_Nama_OP)
                        .addComponent(Form_Username_OP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Form_Password_OP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Form_Nama_OP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Form_Username_OP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Form_Password_OP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Tambah_OP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/add.png"))); // NOI18N
        Tambah_OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah_OPActionPerformed(evt);
            }
        });

        Hapus_OP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/del.png"))); // NOI18N
        Hapus_OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus_OPActionPerformed(evt);
            }
        });

        Edit_Op.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/edit.png"))); // NOI18N
        Edit_Op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_OpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_operatorLayout = new javax.swing.GroupLayout(panel_operator);
        panel_operator.setLayout(panel_operatorLayout);
        panel_operatorLayout.setHorizontalGroup(
            panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operatorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_operatorLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Tambah_OP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Edit_Op)
                        .addGap(6, 6, 6)
                        .addComponent(Hapus_OP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_operatorLayout.setVerticalGroup(
            panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operatorLayout.createSequentialGroup()
                .addGroup(panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_operatorLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tambah_OP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Edit_Op, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hapus_OP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_operatorLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        Content_Layer.add(panel_operator, "card2");

        Panel_Navigation.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Navigation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_Navigation.setPreferredSize(new java.awt.Dimension(722, 99));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-layanan.png"))); // NOI18N
        jLabel11.setText("Layanan");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        tombol_isi_dt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-home.png"))); // NOI18N
        tombol_isi_dt1.setText("Home");
        tombol_isi_dt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombol_isi_dt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tombol_isi_dt1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tombol_isi_dt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_isi_dt1MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-barang.png"))); // NOI18N
        jLabel12.setText("Barang");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-operator.png"))); // NOI18N
        jLabel19.setText("Operator");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-about.png"))); // NOI18N
        jLabel20.setText("Tentang");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-logout.png"))); // NOI18N
        jLabel23.setText("Keluar");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_NavigationLayout = new javax.swing.GroupLayout(Panel_Navigation);
        Panel_Navigation.setLayout(Panel_NavigationLayout);
        Panel_NavigationLayout.setHorizontalGroup(
            Panel_NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NavigationLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(tombol_isi_dt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addContainerGap())
        );
        Panel_NavigationLayout.setVerticalGroup(
            Panel_NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NavigationLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel_NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombol_isi_dt1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content_Layer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Panel_Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content_Layer, javax.swing.GroupLayout.PREFERRED_SIZE, 432, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_layActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_layActionPerformed
        tambah();
        tabel_layanan();
        tampil_tabel_layanan();
    }//GEN-LAST:event_add_layActionPerformed

    private void delete_layActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_layActionPerformed
    hapus();
    tabel_layanan();
    tampil_tabel_layanan();
    }//GEN-LAST:event_delete_layActionPerformed

    private void update_layActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_layActionPerformed
        if(form_nama_lay.getText().length()==0||form_harga_lay.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Form tidak boleh kosong");
        }else{
            update();
            tabel_layanan();
            tampil_tabel_layanan();
        }
    }//GEN-LAST:event_update_layActionPerformed

    private void tabellayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellayananMouseClicked
        int baris = tabellayanan.getSelectedRow();
        String nama = String.valueOf(tabellayanan.getModel().getValueAt(baris, 1));
        String harga = String.valueOf(tabellayanan.getModel().getValueAt(baris, 2));
        form_nama_lay.setText(nama);
        form_harga_lay.setText(harga);
    }//GEN-LAST:event_tabellayananMouseClicked

    private void add_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_brgActionPerformed
        tambah();
        tabel_barang();
        tampil_tabel_barang();
    }//GEN-LAST:event_add_brgActionPerformed

    private void delete_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_brgActionPerformed
        hapus();
        tabel_barang();
        tampil_tabel_barang();
    }//GEN-LAST:event_delete_brgActionPerformed

    private void update_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_brgActionPerformed
        if(form_nama_brg.getText().length()==0||form_harga_brg.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Form tidak boleh kosong");
        }else{
            update();
            tabel_barang();
            tampil_tabel_barang();
        }
    }//GEN-LAST:event_update_brgActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        int baris = tabelbarang.getSelectedRow();
        String nama = String.valueOf(tabelbarang.getModel().getValueAt(baris, 1));
        String harga = String.valueOf(tabelbarang.getModel().getValueAt(baris, 2));
        form_nama_brg.setText(nama);
        form_harga_brg.setText(harga);
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void tombol_isi_dt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_isi_dt1MouseClicked
        panel_barang.setVisible(false);
        panel_layanan.setVisible(false);
        panel_home.setVisible(true);
        panel_operator.setVisible(false);
    }//GEN-LAST:event_tombol_isi_dt1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        
        pilih = 1;
        panel_barang.setVisible(true);
        panel_layanan.setVisible(false);
        panel_home.setVisible(false);
        panel_operator.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        pilih = 2;
        panel_barang.setVisible(false);
        panel_layanan.setVisible(true);
        panel_home.setVisible(false);
        panel_operator.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(this, "Yakin ingin Keluar Aplikasi?","Keluar",JOptionPane.YES_NO_OPTION);
        if(pilih == JOptionPane.YES_OPTION){
            new login_operator().setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        panel_barang.setVisible(false);
        panel_layanan.setVisible(false);
        panel_home.setVisible(false);
        panel_operator.setVisible(true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        JOptionPane.showMessageDialog(this, "Londry Sukses 2016!");
    }//GEN-LAST:event_jLabel20MouseClicked

    private void Edit_OpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_OpActionPerformed
        if(TabelOperator.getSelectedRow()>0){
            try{
                int row = TabelOperator.getSelectedRow();
                String user = String.valueOf(TabelOperator.getValueAt(row, 2));
                stt = con.createStatement();
                stt.executeUpdate("UPDATE OPERATOR set fullname='"+Form_Nama_OP.getText()
                    +"', username='"+Form_Username_OP.getText()
                    +"', password='"+Form_Password_OP.getText()
                    +"' where username='"+user+"'");
                JOptionPane.showMessageDialog(this, "Berhasil Update Data OP");
                Tabel_Operator();
                Tampil_Tabel_Operator();
                Form_Nama_OP.setText("");Form_Password_OP.setText("");Form_Username_OP.setText("");
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }else JOptionPane.showMessageDialog(this, "Pilih Data Dulu");
    }//GEN-LAST:event_Edit_OpActionPerformed

    private void Hapus_OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus_OPActionPerformed
        if(TabelOperator.getSelectedRow()>0){
            try{
                int row = TabelOperator.getSelectedRow();
                String user = String.valueOf(TabelOperator.getValueAt(row, 2));
                stt = con.createStatement();
                stt.executeUpdate("DELETE FROM OPERATOR where username='"+user+"'");
                JOptionPane.showMessageDialog(this, "Berhasil Hapus Data OP");
                Tabel_Operator();
                Tampil_Tabel_Operator();
                Form_Nama_OP.setText("");Form_Password_OP.setText("");Form_Username_OP.setText("");
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }else JOptionPane.showMessageDialog(this, "Pilih Data Dulu");
    }//GEN-LAST:event_Hapus_OPActionPerformed

    private void Tambah_OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah_OPActionPerformed
        if(!(Form_Nama_OP.getText().equals("")||Form_Password_OP.getText().equals("")
            ||Form_Username_OP.getText().equals(""))){
        try{
            stt = con.createStatement();
            rss = stt.executeQuery("SELECT * FROM operator where username='"
                +Form_Username_OP.getText()+"'");
            if(rss.next()){
                JOptionPane.showMessageDialog(this, "User Sudah Ada");
                Form_Username_OP.setText("");Form_Username_OP.requestFocus();
            }else{
                stt.executeUpdate("INSERT INTO OPERATOR set fullname='"
                    +Form_Nama_OP.getText()+"', username='"
                    +Form_Username_OP.getText()+"', password='"
                    +Form_Password_OP.getText()+"', level=2");
                JOptionPane.showMessageDialog(this, "Berhasil Simpan Data OP");
                Tabel_Operator();
                Tampil_Tabel_Operator();
                Form_Nama_OP.setText("");Form_Password_OP.setText("");Form_Username_OP.setText("");
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        }else JOptionPane.showMessageDialog(this, "Form Tidak Boleh Kosong");
    }//GEN-LAST:event_Tambah_OPActionPerformed

    private void Form_Password_OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_Password_OPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Form_Password_OPActionPerformed

    private void TabelOperatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelOperatorMouseClicked
        // TODO add your handling code here:
        int baris = TabelOperator.getSelectedRow();
        Form_Nama_OP.setText(String.valueOf(TabelOperator.getValueAt(baris, 1)));
        Form_Username_OP.setText(String.valueOf(TabelOperator.getValueAt(baris, 2)));
        Form_Password_OP.setText(String.valueOf(TabelOperator.getValueAt(baris, 3)));
    }//GEN-LAST:event_TabelOperatorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_barang_layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_barang_layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_barang_layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_barang_layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_barang_layanan().setVisible(true);
            }
        });
    }
    private void tabel_barang(){
        modelbarang = new DefaultTableModel();
        tabelbarang.setModel(modelbarang);
        modelbarang.addColumn("Id");
        modelbarang.addColumn("Nama Barang");
        modelbarang.addColumn("Harga");
    }
    private void tabel_layanan(){
        modellay = new DefaultTableModel();
        tabellayanan.setModel(modellay);
        modellay.addColumn("Id");
        modellay.addColumn("Nama Layanan");
        modellay.addColumn("Harga");
    }
    private void tampil_tabel_layanan(){
        try{
            stt = con.createStatement();
            String sql = "Select * from layanan";
            rss = stt.executeQuery(sql);
            while(rss.next()){
                Object[] o = new Object[10];
                o[0] = rss.getString(1);
                o[1] = rss.getString(2);
                o[2] = rss.getString(3);
                modellay.addRow(o);
            }
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    private void tampil_tabel_barang(){
        try{
            stt = con.createStatement();
            String sql = "Select * from barang";
            rss = stt.executeQuery(sql);
            while(rss.next()){
                Object[] o = new Object[10];
                o[0] = rss.getString(1);
                o[1] = rss.getString(2);
                o[2] = rss.getString(3);
                modelbarang.addRow(o);
            }
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private void tambah(){
        String namakolom1 = null, namakolom2 = null, namatabel = null;
        String namaform = null, hargaform = null;
        if(pilih==2){ 
                namakolom1 = "nama_layanan";
                namakolom2 = "harga_layanan";
                namatabel = "layanan";
                namaform = form_nama_lay.getText();
                hargaform = form_harga_lay.getText();
            }else if(pilih==1){
                namakolom1 = "nama_barang";
                namakolom2 = "harga_barang";
                namatabel = "barang";
                namaform = form_nama_brg.getText();
                hargaform = form_harga_brg.getText();
            }
        
    if(namaform.equals("")||hargaform.equals("")){
        JOptionPane.showMessageDialog(this, "Form Tidak Boleh Kosong BOR");
    }else{        
        try{
            String nama = namaform;
            String harga = hargaform;
            stt = con.createStatement();
            String sql = "SELECT "+namakolom1+" FROM "+namatabel
                    +" where "+namakolom1+"='"+nama+"'";
            rss = stt.executeQuery(sql);
            if(rss.next()){
                JOptionPane.showMessageDialog(this, "Layanan Sudah ada");
                if(pilih==2){
                form_nama_lay.setText("");
                form_harga_lay.setText("");
                }else{
                form_nama_brg.setText("");
                form_harga_brg.setText("");
                }
                
            }else{
                String sql2 = "INSERT INTO "+namatabel+" set "
                        +namakolom1+"='"+nama+"', "+namakolom2+"='"+harga+"'";
                stt.executeUpdate(sql2);
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    }
    
    private void hapus(){
        try{
            int baris = 0;
            String id=null,idx=null,namatabel=null;
            if(pilih==2){ 
                baris = tabellayanan.getSelectedRow();
                id = String.valueOf(tabellayanan.getModel().getValueAt(baris, 0));
                idx = "id_layanan";
                namatabel = "layanan";
            }else if(pilih==1){
                baris = tabelbarang.getSelectedRow();
                id = String.valueOf(tabelbarang.getModel().getValueAt(baris, 0));
                idx = "id_barang";
                namatabel = "barang";
            }
            stt = con.createStatement();
            String sql = "delete from "+namatabel+" where "+idx+"='"+id+"'";
            stt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Data Berhasil dihapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus");
            System.out.println(e.getMessage());
        }
    }
    
    private void update(){
        
        try{
            String nama = null, harga = null;
            int baris;
            String idx = null, id = null, namatabel = null;
            
            if(pilih==2){
            namatabel = "layanan";
            nama = form_nama_lay.getText();
            harga = form_harga_lay.getText();
            baris = tabellayanan.getSelectedRow();
            idx = String.valueOf(tabellayanan.getModel().getValueAt(baris, 0));
            }else{
            namatabel = "barang";
            nama = form_nama_brg.getText();
            harga = form_harga_brg.getText();
            baris = tabelbarang.getSelectedRow();
            idx = String.valueOf(tabelbarang.getModel().getValueAt(baris, 0));
            }
            
            stt = con.createStatement();
            String sql = "update "+namatabel+" set nama_"+namatabel+"='"+nama
                    +"', harga_"+namatabel+"='"+harga+"' where id_"+namatabel+"='"+idx+"'";
            stt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Data Terupdate");
            if(pilih==2){
                form_nama_lay.setText("");
                form_harga_lay.setText("");
            }else{
                form_nama_brg.setText("");
                form_harga_brg.setText("");
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    private void Tampil_Tabel_Operator(){
        try{
            stt = con.createStatement();
            String sql = "Select * from operator where level=2";
            rss = stt.executeQuery(sql);
            while(rss.next()){
                Object[] o = new Object[4];
                o[0] = rss.getString("id_operator");
                o[1] = rss.getString("fullname");
                o[2] = rss.getString("username");
                o[3] = rss.getString("password");
                ModelOperator.addRow(o);
            }
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    private void Tabel_Operator(){
        ModelOperator = new DefaultTableModel();
        TabelOperator.setModel(ModelOperator);
        ModelOperator.addColumn("Id");
        ModelOperator.addColumn("Nama");
        ModelOperator.addColumn("Username");
        ModelOperator.addColumn("Password");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content_Layer;
    private javax.swing.JButton Edit_Op;
    private javax.swing.JTextField Form_Nama_OP;
    private javax.swing.JTextField Form_Password_OP;
    private javax.swing.JTextField Form_Username_OP;
    private javax.swing.JButton Hapus_OP;
    private javax.swing.JPanel Panel_Navigation;
    private javax.swing.JTable TabelOperator;
    private javax.swing.JButton Tambah_OP;
    private javax.swing.JButton add_brg;
    private javax.swing.JButton add_lay;
    private javax.swing.JButton delete_brg;
    private javax.swing.JButton delete_lay;
    private javax.swing.JTextField form_harga_brg;
    private javax.swing.JTextField form_harga_lay;
    private javax.swing.JTextField form_nama_brg;
    private javax.swing.JTextField form_nama_lay;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panel_barang;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_layanan;
    private javax.swing.JPanel panel_operator;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTable tabellayanan;
    private javax.swing.JLabel tombol_isi_dt1;
    private javax.swing.JButton update_brg;
    private javax.swing.JButton update_lay;
    // End of variables declaration//GEN-END:variables
}
