package project;
import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import project.awalan;

public class isi_data extends javax.swing.JFrame {
    /**
     * Creates new form utama
     */
    Connection con = koneksi.getConnection();
    Statement stt;
    ResultSet rss;
    DefaultTableModel Model_Tabel_Item = new DefaultTableModel();
    
    private String tgl, status,is_empty_date;
    private double totalbayar;
    private boolean check_selesai,on,disc;
    public String id_kasir;     
    
    public isi_data() {
        initComponents();
        SetIdKasir();
        SetIdTransaksi();
        tglskrg();
        tampil_barang();
        tampil_layanan();
        sets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        formnama = new javax.swing.JTextField();
        form_jln = new javax.swing.JTextField();
        form_tlp = new javax.swing.JTextField();
        form_kec = new javax.swing.JTextField();
        form_kota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        combobarang = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        kuantitas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        combolayanan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        id_transaksi = new javax.swing.JTextField();
        btn_Tambah_Item = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_item = new javax.swing.JTable();
        Hapus_Item = new javax.swing.JButton();
        Total_Harga_Transaksi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TanggalKeluarChooser = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        tanggalmasuk = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Selesai = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Panel_Navigation1 = new javax.swing.JPanel();
        menu_transaksi = new javax.swing.JLabel();
        menu_home = new javax.swing.JLabel();
        menu_isi_data = new javax.swing.JLabel();
        menu_konsumen = new javax.swing.JLabel();
        menu_tentang = new javax.swing.JLabel();
        menu_keluar = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel2.setText("Nama      :");

        jLabel3.setText("Alamat    :");

        jLabel4.setText("Telepon  :");

        formnama.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        form_jln.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        form_jln.setForeground(new java.awt.Color(153, 153, 153));
        form_jln.setText("Jalan");
        form_jln.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_jlnMouseClicked(evt);
            }
        });
        form_jln.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                form_jlnFocusGained(evt);
            }
        });

        form_kec.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        form_kec.setForeground(new java.awt.Color(153, 153, 153));
        form_kec.setText("Kecamatan");
        form_kec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_kecMouseClicked(evt);
            }
        });
        form_kec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                form_kecFocusGained(evt);
            }
        });

        form_kota.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        form_kota.setForeground(new java.awt.Color(153, 153, 153));
        form_kota.setText("Kota");
        form_kota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_kotaMouseClicked(evt);
            }
        });
        form_kota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                form_kotaFocusGained(evt);
            }
        });

        jLabel5.setText("Barang              :");

        jLabel14.setText("Harga       :");

        total.setEditable(false);
        total.setText("0.0");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel1.setText("Harga Diskon :");

        diskon.setText("0");

        combobarang.setMaximumRowCount(5);
        combobarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combobarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobarangItemStateChanged(evt);
            }
        });

        jLabel8.setText("Kuantitas          :");

        kuantitas.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                kuantitasCaretUpdate(evt);
            }
        });

        jLabel9.setText("Kg");

        combolayanan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combolayananItemStateChanged(evt);
            }
        });

        jLabel7.setText("Layanan            :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("* Potongan harga 10% bila lebih dari 10 Kg");

        jLabel13.setText("No. Transaksi");

        id_transaksi.setEditable(false);
        id_transaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_transaksi.setForeground(new java.awt.Color(255, 0, 0));
        id_transaksi.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_Tambah_Item.setText("+ Tambah Item");
        btn_Tambah_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tambah_ItemActionPerformed(evt);
            }
        });

        tabel_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Barang", "Nama Layanan", "Harga"
            }
        ));
        tabel_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_itemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_item);

        Hapus_Item.setText(" HapusItem");
        Hapus_Item.setEnabled(false);
        Hapus_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus_ItemActionPerformed(evt);
            }
        });

        Total_Harga_Transaksi.setEditable(false);
        Total_Harga_Transaksi.setText("0.0");

        jLabel15.setText("Total          :");

        TanggalKeluarChooser.setDateFormatString("yyyy-MM-dd HH:mm:ss");

        tanggalmasuk.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel7))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combobarang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combolayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(153, 153, 153)
                                .addComponent(jLabel13)
                                .addGap(10, 10, 10)
                                .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel15)
                                        .addGap(8, 8, 8)
                                        .addComponent(Total_Harga_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(10, 10, 10)
                                                    .addComponent(formnama, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(10, 10, 10)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(form_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(form_jln, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(6, 6, 6)
                                                            .addComponent(form_kec, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(10, 10, 10)
                                        .addComponent(form_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(12, 12, 12)
                                        .addComponent(kuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(TanggalKeluarChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_Tambah_Item)
                                        .addGap(6, 6, 6)
                                        .addComponent(Hapus_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(form_jln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_kec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(form_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(combobarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(combolayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TanggalKeluarChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Tambah_Item)
                            .addComponent(Hapus_Item))))
                .addGap(16, 16, 16)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Total_Harga_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        Selesai.setText("Finish");
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });

        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/400_F_46645327_ySaSgxjA2fDdz695qxJ94l0RAfhVuqwi.jpg"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selesai)
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Selesai)
                    .addComponent(jButton6)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Navigation1.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Navigation1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_Navigation1.setPreferredSize(new java.awt.Dimension(722, 99));

        menu_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-transaksi.png"))); // NOI18N
        menu_transaksi.setText("Transaksi");
        menu_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_transaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_transaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_transaksiMouseClicked(evt);
            }
        });

        menu_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-home.png"))); // NOI18N
        menu_home.setText("Home");
        menu_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_homeMouseClicked(evt);
            }
        });

        menu_isi_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-form.png"))); // NOI18N
        menu_isi_data.setText("Form");
        menu_isi_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_isi_data.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_isi_data.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_isi_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_isi_dataMouseClicked(evt);
            }
        });

        menu_konsumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-konsumen.png"))); // NOI18N
        menu_konsumen.setText("Konsumen");
        menu_konsumen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_konsumen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_konsumen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_konsumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_konsumenMouseClicked(evt);
            }
        });

        menu_tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-about.png"))); // NOI18N
        menu_tentang.setText("Tentang");
        menu_tentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_tentang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_tentang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_tentangMouseClicked(evt);
            }
        });

        menu_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon-logout.png"))); // NOI18N
        menu_keluar.setText("Keluar");
        menu_keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_keluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_keluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_keluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_Navigation1Layout = new javax.swing.GroupLayout(Panel_Navigation1);
        Panel_Navigation1.setLayout(Panel_Navigation1Layout);
        Panel_Navigation1Layout.setHorizontalGroup(
            Panel_Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Navigation1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(menu_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_isi_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_transaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_konsumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_tentang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_keluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Navigation1Layout.setVerticalGroup(
            Panel_Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Navigation1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Panel_Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_home)
                    .addComponent(menu_isi_data)
                    .addComponent(menu_transaksi)
                    .addComponent(menu_konsumen)
                    .addComponent(menu_tentang)
                    .addComponent(menu_keluar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Navigation1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Navigation1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combolayananItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combolayananItemStateChanged
        if(on){Read_data();}
    }//GEN-LAST:event_combolayananItemStateChanged

    private void kuantitasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_kuantitasCaretUpdate
        Read_data();
    }//GEN-LAST:event_kuantitasCaretUpdate

    private void combobarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobarangItemStateChanged
        if(on){Read_data();}
    }//GEN-LAST:event_combobarangItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        formnama.setText("");
        form_jln.setText("");
        form_kec.setText("");
        form_kota.setText("");
        form_tlp.setText("");
        kuantitas.setText("");
        diskon.setText("");
        total.setText("0.0");
        Total_Harga_Transaksi.setText("0.0");
        combobarang.setSelectedIndex(0);
        combolayanan.setSelectedIndex(0);
        if(tabel_item.getRowCount()>0){
            for(int i = 0;i<=tabel_item.getRowCount();i++){
            Model_Tabel_Item.removeRow(0);
            if(tabel_item.getRowCount()==1){
                Model_Tabel_Item.removeRow(0);
            }   
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiActionPerformed
        if(!(formnama.getText().equals("") || form_jln.getText().equals("") ||
            form_kec.getText().equals("") || form_kota.getText().equals("") ||
            form_tlp.getText().equals(""))){
            if (tabel_item.getRowCount()>0) {
                is_empty_date = String.valueOf(TanggalKeluarChooser.getDate());
                if(is_empty_date=="null"){
                    JOptionPane.showMessageDialog(null, "Pilih Tanggal Keluar");
                    TanggalKeluarChooser.requestFocus();
                }else{
                    check_selesai = true;
                    Read_data();
                    dispose();
                    new transaksi().setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Tambah Item!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Form Tidak Boleh Kosong");
        }
    }//GEN-LAST:event_SelesaiActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void form_kotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_form_kotaFocusGained
        UbahFont();
    }//GEN-LAST:event_form_kotaFocusGained

    private void form_kotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_kotaMouseClicked
        UbahFont();
    }//GEN-LAST:event_form_kotaMouseClicked

    private void form_kecFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_form_kecFocusGained
        UbahFont();
    }//GEN-LAST:event_form_kecFocusGained

    private void form_kecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_kecMouseClicked
        UbahFont();
    }//GEN-LAST:event_form_kecMouseClicked

    private void form_jlnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_form_jlnFocusGained
        UbahFont();
    }//GEN-LAST:event_form_jlnFocusGained

    private void form_jlnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_jlnMouseClicked
        UbahFont();
    }//GEN-LAST:event_form_jlnMouseClicked

    private void btn_Tambah_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tambah_ItemActionPerformed
        double totals = 0, totalharga = 0;
        Object[] o = new Object[3];
        o[0] = combobarang.getSelectedItem();
        o[1] = combolayanan.getSelectedItem();
        if(disc){
            totals = totalbayar;
            o[2] = totalbayar;
        }else{
            totals = Double.parseDouble(String.valueOf(total.getText()));
            o[2] = total.getText();
        }
        totalharga = Double.parseDouble(String.valueOf(Total_Harga_Transaksi.getText()))+totals;
        Total_Harga_Transaksi.setText(""+totalharga);
        Model_Tabel_Item.addRow(o);
        disc = false;
    }//GEN-LAST:event_btn_Tambah_ItemActionPerformed

    private void tabel_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_itemMouseClicked
        Hapus_Item.setEnabled(true);
    }//GEN-LAST:event_tabel_itemMouseClicked

    private void Hapus_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus_ItemActionPerformed
        int baris = tabel_item.getSelectedRow();
        Model_Tabel_Item.removeRow(baris);
        Hapus_Item.setEnabled(false);
    }//GEN-LAST:event_Hapus_ItemActionPerformed

    private void menu_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_transaksiMouseClicked
        new transaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_transaksiMouseClicked

    private void menu_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_homeMouseClicked
        new awalan().setVisible(true);dispose();
    }//GEN-LAST:event_menu_homeMouseClicked

    private void menu_isi_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_isi_dataMouseClicked
        new isi_data().setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_isi_dataMouseClicked

    private void menu_konsumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_konsumenMouseClicked
        new konsumen().setVisible(true);dispose();
    }//GEN-LAST:event_menu_konsumenMouseClicked

    private void menu_tentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_tentangMouseClicked
        JOptionPane.showMessageDialog(this, "Londry Sukses 2016!");
    }//GEN-LAST:event_menu_tentangMouseClicked

    private void menu_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keluarMouseClicked
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(this, "Yakin ingin Keluar Aplikasi?","Keluar",JOptionPane.YES_NO_OPTION);
        if(pilih == JOptionPane.YES_OPTION){
            new login_operator().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_menu_keluarMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new awalan().setVisible(true); dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isi_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isi_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isi_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isi_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new isi_data().setVisible(true);
            }
        });
    }
    //
    
    private void Read_data(){
        Statement sttRead;
        ResultSet rssRead;
        String barang = String.valueOf(combobarang.getSelectedItem());
        String layanan = String.valueOf(combolayanan.getSelectedItem());
        double  hargabarang, hargalayanan,tmp;
        double  kuanti;
        if(kuantitas.getText().equals("")){
            kuanti = 0;
        }else{
            kuanti = Double.parseDouble(kuantitas.getText());
        }
        
        int id_bar,id_lay;
                
        try{    
            sttRead = con.createStatement();
            String sqlRead = "SElECT * FROM barang,layanan where nama_barang='"
                    +barang+"' and nama_layanan='"+layanan+"'";
            rssRead = sttRead.executeQuery(sqlRead);
            
            rssRead.next();
               hargabarang = Double.parseDouble(rssRead.getString("harga_barang"));
               hargalayanan = Double.parseDouble(rssRead.getString("harga_layanan"));
               id_bar = rssRead.getInt("id_barang");
               id_lay = rssRead.getInt("id_layanan");
               totalbayar = (hargabarang*hargalayanan)*kuanti;               
               total.setText(String.valueOf(totalbayar));
            //Hitung Diskon jika berat lebih dari 10  
            if(kuanti>=10){
                disc = true;
                tmp = (totalbayar*10)/100;//Diskon 10%
                totalbayar= totalbayar-tmp;
                diskon.setText(String.valueOf(totalbayar));
            }else{
                diskon.setText("0");
            }
            if(check_selesai){
                totalbayar = Double.parseDouble(Total_Harga_Transaksi.getText());
            input_data(id_bar, id_lay, totalbayar);
            }
        }catch(SQLException e){
            System.out.println("Masalah \n "+ e.getMessage());
        }   
    }
    private void input_data(int id_b, int id_l, double ttl){
        SimpleDateFormat formatdb= new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        tgl = formatdb.format(TanggalKeluarChooser.getDate());
        String nama = formnama.getText();
        String jln = form_jln.getText();
        String kec = form_kec.getText();
        String kota = form_kota.getText();
        String tlp = form_tlp.getText();
        int id;
        try{
            stt = con.createStatement();
            //INSERT TABEL KONSUMEN
            String sql = "INSERT INTO konsumen set nama='"+nama+"', telepon='"+tlp
                    +"', jalan='"+jln+"', kota='"+kota+"', kecamatan='"+kec+"'";
            stt.executeUpdate(sql); 
            //Read Data Konsumen
            rss = stt.executeQuery("SELECT * from konsumen where telepon='"+tlp+"'");
            rss.next();
                id = rss.getInt(1); //ambil id konsumen untuk query transaksi
            rss.close();
            
            Pilih_status(); //Menentukan status data baru berdasarkan method
            
            //INSERT TABEL TRANSAKSI
            String sql2 = "INSERT INTO transaksi Values ("+id+",NULL,NULL,'"+tgl
                    +"','"+status+"',"+id_kasir+","+ttl+")";
            stt.executeUpdate(sql2);
            stt.close();
            
            Input_Item();        
            JOptionPane.showMessageDialog(this, "Data Berhasil disimpan");
        }catch(SQLException e){
            System.out.println("Error bor"+e.getMessage());
        }
}
    public void tglskrg(){
        //TGL MASUK
        Date skrg= new Date();
        SimpleDateFormat format= new SimpleDateFormat("EEEE, dd-MM-yyyy");
        tanggalmasuk.setText(format.format(skrg));
//        //TGL KELUAR
//        long tambil = System.currentTimeMillis()+(36000000*4);
//        long tambil2 = System.currentTimeMillis()+(36000000*4);
//        Date ambil = new Date();
//        SimpleDateFormat format2= new SimpleDateFormat("EEEE, dd-MM-yyyy");

    }
    private void tampil_barang(){
        
        DefaultComboBoxModel modelbarang = new DefaultComboBoxModel();
        combobarang.setModel(modelbarang);
        try{
            stt = con.createStatement();
            String sql = "SELECT nama_barang FROM barang";
            rss = stt.executeQuery(sql);
            while(rss.next()){
            modelbarang.addElement(rss.getString("nama_barang"));
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    private void tampil_layanan(){
        
        DefaultComboBoxModel modellayanan = new DefaultComboBoxModel();
        combolayanan.setModel(modellayanan);
        try{
            stt = con.createStatement();
            String sql = "SELECT nama_layanan FROM layanan";
            rss = stt.executeQuery(sql);
            while(rss.next()){
            modellayanan.addElement(rss.getString("nama_layanan"));
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    private void SetIdKasir(){
        Object[] op = login_operator.getKasir();
        id_kasir = ""+op[0];
    }
    private void SetIdTransaksi(){
        try{
            stt = con.createStatement();
//            String sql = "SELECT transaksi.id_transaksi,item.id_item FROM Transaksi,item";
            String sql = "SELECT transaksi.id_transaksi FROM Transaksi";
            rss = stt.executeQuery(sql);
            if(rss.next()){
            rss.last();
            int id = rss.getInt("id_transaksi");
            id++;
            id_transaksi.setText(String.valueOf(id));
            }else{
                id_transaksi.setText("1");
            }
            rss.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
        
    }
    private void sets(){
        //method ini digunakan untuk mencegah error pada saat menampilkan
        //combo box layanan dan barang, dimana keduanya memiliki ev caretUpdate
        on = true;
        tabel_item.setModel(Model_Tabel_Item);
        Model_Tabel_Item.addColumn("Nama Barang");
        Model_Tabel_Item.addColumn("Nama Layanan");
        Model_Tabel_Item.addColumn("Harga");
    }
    private void UbahFont(){
        Font biasa = new Font ("Verdana", Font.PLAIN,11);
        Font fontawal = null;
        if(form_jln.isFocusOwner()){
            fontawal = form_jln.getFont();
            if(!biasa.equals(fontawal)){
                form_jln.setText("");
                form_jln.setFont(biasa);
                form_jln.setForeground(Color.black);
            }
        }else
        if(form_kec.isFocusOwner()){
            fontawal = form_kec.getFont();
            if(!biasa.equals(fontawal)){
                form_kec.setText("");
                form_kec.setFont(biasa);
                form_kec.setForeground(Color.black);
            }
        }else
        if(form_kota.isFocusOwner()){
            fontawal = form_kota.getFont();
            if(!biasa.equals(fontawal)){
                form_kota.setText("");
                form_kota.setFont(biasa);
                form_kota.setForeground(Color.black);
            }
        }
    }
    private void Input_Item(){
        
        //INSERT TABLE ITEM
        try{
        stt = con.createStatement();
            String nama_barang, nama_layanan, harga, id_trans, id_barang,id_layanan;
            for(int baris = 0; baris<tabel_item.getRowCount();baris++){
                nama_barang = (String) tabel_item.getValueAt(baris, 0);
                nama_layanan = (String) tabel_item.getValueAt(baris, 1);
                String sql = "SELECT * FROM barang,layanan where nama_barang='"
                        +nama_barang+"' and nama_layanan='"+nama_layanan+"'";
                rss = stt.executeQuery(sql);
                rss.next();
                id_barang = rss.getString("id_barang");
                id_layanan = rss.getString("id_layanan");
                harga = String.valueOf(tabel_item.getValueAt(baris, 2));
                id_trans = id_transaksi.getText();
                
                String sql3 = "INSERT INTO ITEM values "
                        +"(NULL,'"+id_barang+"','"+id_layanan+"','"+id_trans+"',"
                        +harga+")";
                stt.executeUpdate(sql3);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
            System.out.println("Error Mudul Input Item");
        }
    }
    private void Pilih_status(){
            
        try{
            stt = con.createStatement();
            rss = stt.executeQuery("SELECT status FROM transaksi "
                    + "where status='Sedang diproses'");
            //jika data yg berstatus sedang diproses lebih atau sams dengan 7, 
            //maka data selanjutnya berstatus belum diproses
            if(rss.getRow()>=7){
                status = "Belum diproses";
            }else{
                status = "Sedang diproses";
            }
            rss.close();
        }catch(Exception e){
            System.out.println("Pilih Status Error \n"+e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus_Item;
    private javax.swing.JPanel Panel_Navigation1;
    private javax.swing.JButton Selesai;
    private com.toedter.calendar.JDateChooser TanggalKeluarChooser;
    private javax.swing.JTextField Total_Harga_Transaksi;
    private javax.swing.JButton btn_Tambah_Item;
    private javax.swing.JComboBox<String> combobarang;
    private javax.swing.JComboBox<String> combolayanan;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField form_jln;
    private javax.swing.JTextField form_kec;
    private javax.swing.JTextField form_kota;
    private javax.swing.JTextField form_tlp;
    private javax.swing.JTextField formnama;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField kuantitas;
    private javax.swing.JLabel menu_home;
    private javax.swing.JLabel menu_isi_data;
    private javax.swing.JLabel menu_keluar;
    private javax.swing.JLabel menu_konsumen;
    private javax.swing.JLabel menu_tentang;
    private javax.swing.JLabel menu_transaksi;
    private javax.swing.JTable tabel_item;
    private javax.swing.JTextField tanggalmasuk;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

}
